<?php

/*
 * This file is part of davServices.
 *
 * (c) Felix Böck <https://dav.services>
 *
 * Licensed under the Apache License, Version 2.0.
 * For the full copyright and license information, see the LICENSE file.
 */

declare(strict_types=1);

namespace DavServices\VObject\TimeZone;

use DateTimeImmutable;
use DateTimeZone;
use DavServices\VObject\Component;
use DavServices\VObject\ParseError;
use DavServices\VObject\Property;
use DavServices\VObject\Recur\ExpandedSet;
use DavServices\VObject\Recur\Rule;
use DavServices\VObject\Value\Date;
use DavServices\VObject\Value\DateTime;
use DavServices\VObject\Value\UtcOffset;
use Generator;

/**
 * One `STANDARD` or `DAYLIGHT` sub-component of a `VTIMEZONE`: an observance,
 * and the moments at which it begins (RFC 5545 §3.6.5).
 *
 * **An observance is a constant offset and a set of onsets.** Which of them
 * applies at a given moment is {@see Definition}'s question, because it takes
 * all of them together; this class answers only about itself.
 *
 * ## The onset is the local time taken in the offset *before* it
 *
 * Four sentences of §3.6.5 say the same thing, and together they are this
 * class's whole arithmetic:
 *
 * > The mandatory "DTSTART" property gives the effective onset date and local
 * > time for the time zone sub-component definition. "DTSTART" in this usage
 * > MUST be specified as a date with a local time value.
 *
 * > The mandatory "TZOFFSETFROM" property gives the UTC offset that is in use
 * > when the onset of this time zone observance begins. "TZOFFSETFROM" is
 * > combined with "DTSTART" to define the effective onset for the time zone
 * > sub-component definition.
 *
 * > The "DTSTART" and the "TZOFFSETFROM" properties MUST be used when
 * > generating the onset DATE-TIME values (instances) from the "RRULE".
 *
 * > "RDATE" in this usage MUST be specified as a date with local time value,
 * > relative to the UTC offset specified in the "TZOFFSETFROM" property.
 *
 * So an onset's moment is `DTSTART − TZOFFSETFROM`, and the same for every
 * instance a rule or an `RDATE` adds. **Using `TZOFFSETTO` instead** — the
 * offset the observance brings, which is the one a reader first reaches for —
 * moves every change of offset by the difference of the two, an hour in most
 * of the world.
 *
 * ## The bound is in UTC, and the expansion is not
 *
 * > If observance is known to have an effective end date, the "UNTIL"
 * > recurrence rule parameter MUST be used to specify the last valid onset of
 * > this observance (i.e., the UNTIL DATE-TIME will be equal to the last
 * > instance generated by the recurrence pattern). It MUST be specified in
 * > UTC time.
 *
 * The expansion compares an instance with its bound **on the wall clock**, and
 * {@see \DavServices\VObject\Recur\Iterator} sets out why: §3.8.5.3's own
 * published answers require it. Here the bound is an instant, and the two
 * readings part company east of Greenwich — an onset at 02:00 local in `+0100`
 * is 01:00 UTC, so a bound naming that very instant would look like 01:00 to a
 * wall-clock comparison and drop the onset it was written to keep.
 *
 * **So the bound is converted before the expansion sees it**, by the same
 * `TZOFFSETFROM` the onsets are measured in. The alternative — teaching the
 * expansion a second kind of comparison — would put a time zone's exception
 * into the engine every other rule in the memo also uses.
 *
 * ## Why the onsets are read as they are needed
 *
 * A rule without an `UNTIL` or a `COUNT` has no last onset, so the set cannot
 * be materialised; but a question is always about a particular moment, and
 * only the onsets up to it matter. The expansion is therefore held open and
 * read far enough to answer, and what has been read is kept — **so a run of
 * questions about later and later moments costs each onset once**, which is
 * what a reader walking a recurrence set does.
 *
 * The expansion's own hard limit (R-RRULE-04) still holds: a question about a
 * moment far enough away passes it, and that is a refusal rather than an
 * answer from a half-expanded set.
 */
final class Observance
{
    /**
     * The onsets, in order, read no further than a question has needed.
     *
     * @var Generator<int, Date|DateTime>
     */
    private Generator $onsets;

    /**
     * Every onset read so far, in order.
     *
     * @var list<DateTimeImmutable>
     */
    private array $read = [];

    private function __construct(
        private readonly int $offset,
        private readonly int $offsetBefore,
        private readonly ?string $name,
        private readonly DateTimeImmutable $first,
        ExpandedSet $onsets,
    ) {
        $this->onsets = $onsets->instances();
    }

    /**
     * The observance a sub-component describes.
     *
     * @param int $iterations The hard limit the expansion is given (R-CAL-08)
     *
     * @throws ParseError If the sub-component leaves out one of the three
     *                    properties §3.6.5 makes mandatory, or names a moment
     *                    where the memo requires a local time
     */
    public static function of(Component $observance, int $iterations): self
    {
        $start = self::aLocalTimeIn($observance, 'DTSTART');
        $offsetBefore = self::anOffsetIn($observance, 'TZOFFSETFROM');
        $offset = self::anOffsetIn($observance, 'TZOFFSETTO');
        $dates = self::datesIn($observance);

        return new self(
            $offset,
            $offsetBefore,
            $observance->property('TZNAME')?->value(),
            self::earliestOf([$start, ...$dates], $offsetBefore),
            new ExpandedSet(
                $start,
                self::rulesIn($observance, $offsetBefore),
                $dates,
                [],
                [],
                $iterations,
            ),
        );
    }

    /**
     * The offset this observance keeps, `TZOFFSETTO`, in seconds.
     */
    public function offset(): int
    {
        return $this->offset;
    }

    /**
     * The offset that was in use before it began, `TZOFFSETFROM`, in seconds.
     *
     * **This is the definition's own answer for any moment before every
     * onset** — "the UTC offset that is in use when the onset of this time
     * zone observance begins" — and the reason the memo says of its
     * `DTSTART`-only example that it is "only suitable for a recurring event
     * that starts on or later than" the first onset.
     */
    public function offsetBefore(): int
    {
        return $this->offsetBefore;
    }

    /**
     * The customary name of the zone in this observance, `TZNAME`, or null
     * where it gives none. It is optional, and "could be used for displaying
     * dates".
     */
    public function name(): ?string
    {
        return $this->name;
    }

    /**
     * The first moment at which this observance ever begins.
     *
     * **Read without expanding anything**: §3.8.5.3 makes `DTSTART` the first
     * instance of every rule, so only an `RDATE` written before it can come
     * earlier.
     */
    public function first(): DateTimeImmutable
    {
        return $this->first;
    }

    /**
     * The last onset of this observance at or before a moment, or null where
     * it had not begun yet.
     *
     * **At or before**, because `DTSTART` "gives the *effective* onset": the
     * second an onset names already belongs to it.
     *
     * **A moment before the first onset is answered without expanding
     * anything**, {@see self::first()} being known from the written values
     * alone. It is the one question a definition is asked about every moment
     * its observances do not cover, so it should not cost an expansion.
     *
     * @throws \DavServices\VObject\Recur\TooManyIterations If reaching the
     *                                                      moment passes the
     *                                                      expansion's limit
     */
    public function lastOnsetUpTo(DateTimeImmutable $moment): ?DateTimeImmutable
    {
        if ($moment < $this->first) {
            return null;
        }

        $this->readUpTo($moment);
        $last = null;

        // What has been read is kept, so an earlier question asked after a
        // later one finds onsets past its own moment and steps over them.
        foreach ($this->read as $onset) {
            if ($onset <= $moment) {
                $last = $onset;
            }
        }

        return $last;
    }

    /**
     * Reads every onset up to a moment, and not one further.
     *
     * The onset that lies past the moment is looked at but **not taken**, so
     * it is still the expansion's current one when a later moment asks for
     * it. That is what makes a walk through later and later moments cost each
     * onset once.
     */
    private function readUpTo(DateTimeImmutable $moment): void
    {
        while ($this->onsets->valid()) {
            $next = self::momentOf($this->onsets->current(), $this->offsetBefore);

            if ($next > $moment) {
                return;
            }

            $this->read[] = $next;
            $this->onsets->next();
        }
    }

    /**
     * The earliest of these local times, as a moment.
     *
     * @param non-empty-list<Date|DateTime> $values
     */
    private static function earliestOf(array $values, int $offsetBefore): DateTimeImmutable
    {
        $moments = [];

        foreach ($values as $value) {
            $moments[] = self::momentOf($value, $offsetBefore);
        }

        return min($moments);
    }

    /**
     * The moment a local onset names, which is its wall clock taken in the
     * offset that was in use before it.
     */
    private static function momentOf(Date|DateTime $value, int $offsetBefore): DateTimeImmutable
    {
        $wall = new DateTimeImmutable($value->encode(), new DateTimeZone('UTC'));

        // Moved by the seconds themselves rather than by a written modifier,
        // which is a string PHP has to parse and may refuse.
        return $wall->setTimestamp($wall->getTimestamp() - $offsetBefore);
    }

    /**
     * Every `RDATE` value of the sub-component, each a local time.
     *
     *
     * @throws ParseError If one of them is not a local time
     *
     * @return list<DateTime>
     */
    private static function datesIn(Component $observance): array
    {
        $dates = [];

        foreach ($observance->properties('RDATE') as $property) {
            // §3.8.5.2: the value is "a COMMA-separated list of date-time
            // values", and in this usage every one of them is a local time.
            foreach (explode(',', $property->value()) as $raw) {
                $dates[] = self::aLocalTime($raw, $observance->name(), 'RDATE');
            }
        }

        return $dates;
    }

    /**
     * Every `RRULE` of the sub-component, its bound put on the clock the
     * expansion runs on.
     *
     *
     * @throws ParseError If one of them cannot be read
     *
     * @return list<Rule>
     */
    private static function rulesIn(Component $observance, int $offsetBefore): array
    {
        $rules = [];

        foreach ($observance->properties('RRULE') as $property) {
            $rules[] = Rule::decode(self::onTheOnsetClock($property->value(), $offsetBefore));
        }

        return $rules;
    }

    /**
     * A rule whose `UNTIL` is an instant, rewritten on the local clock the
     * onsets are written in.
     *
     * A bound that is already a local time is left as it stands. The memo
     * requires UTC here, and a value without the `Z` breaks that; but it is
     * then written on the very clock the comparison uses, so its meaning is
     * not in doubt and refusing it would lose a definition that can be read.
     *
     * @throws ParseError If the bound cannot be read at all
     */
    private static function onTheOnsetClock(string $rule, int $offsetBefore): string
    {
        $parts = [];

        // Upper case only, and that is {@see Rule}'s decision rather than a
        // shortcut: §2 of the memo overrides ABNF's case-insensitive literals
        // for a RECUR value, so a lower-case part name never reaches a rule.
        foreach (explode(';', $rule) as $part) {
            $parts[] = str_starts_with($part, 'UNTIL=')
                ? self::boundOnTheOnsetClock($part, $offsetBefore)
                : $part;
        }

        return implode(';', $parts);
    }

    /**
     * An `UNTIL` part on the local clock, where it was written as an instant.
     *
     * @throws ParseError If the bound cannot be read at all
     */
    private static function boundOnTheOnsetClock(string $part, int $offsetBefore): string
    {
        $bound = DateTime::decode(substr($part, 6));

        if (!$bound->isUtc()) {
            return $part;
        }

        $instant = $bound->in(new DateTimeZone('UTC'));
        $local = $instant->setTimestamp($instant->getTimestamp() + $offsetBefore);

        return 'UNTIL=' . $local->format('Ymd\THis');
    }

    /**
     * A property of the sub-component read as a local time.
     *
     * @throws ParseError If it is missing, or is not a local time
     */
    private static function aLocalTimeIn(Component $observance, string $name): DateTime
    {
        return self::aLocalTime(
            self::propertyIn($observance, $name)->value(),
            $observance->name(),
            $name,
        );
    }

    /**
     * A written value read as a local time, as §3.6.5 requires of an onset.
     *
     * @throws ParseError If it is no date and time, or is an instant in UTC
     */
    private static function aLocalTime(string $raw, string $where, string $name): DateTime
    {
        $value = DateTime::decode($raw);

        if ($value->isUtc()) {
            throw new ParseError(sprintf(
                'A %s names its onset as a date with a local time value (RFC 5545 §3.6.5), and its %s "%s" is an instant in UTC.',
                $where,
                $name,
                $raw,
            ));
        }

        return $value;
    }

    /**
     * A property of the sub-component read as a UTC offset.
     *
     * @throws ParseError If it is missing, or is no offset
     */
    private static function anOffsetIn(Component $observance, string $name): int
    {
        return UtcOffset::decode(self::propertyIn($observance, $name)->value())->seconds();
    }

    /**
     * A property §3.6.5 makes mandatory in an observance.
     *
     * @throws ParseError If the sub-component has not got it
     */
    private static function propertyIn(Component $observance, string $name): Property
    {
        $property = $observance->property($name);

        if ($property === null) {
            throw new ParseError(sprintf(
                'A time zone observance names its onset and both its offsets (RFC 5545 §3.6.5), and this %s has no %s.',
                $observance->name(),
                $name,
            ));
        }

        return $property;
    }
}
