<?php

/*
 * This file is part of davServices.
 *
 * (c) Felix Böck <https://dav.services>
 *
 * Licensed under the Apache License, Version 2.0.
 * For the full copyright and license information, see the LICENSE file.
 */

declare(strict_types=1);

namespace DavServices\VObject\Recur;

use ArrayIterator;
use DateTimeImmutable;
use DateTimeZone;
use DavServices\VObject\Component;
use DavServices\VObject\ParseError;
use DavServices\VObject\Value\Date;
use DavServices\VObject\Value\DateTime;
use DavServices\VObject\Value\Period;
use Generator;

/**
 * The recurrence set of one component (RFC 5545 §3.8.5, R-RRULE-02).
 *
 *     foreach (ExpandedSet::of($event)->instances() as $instance) {
 *         echo $instance->encode(), "\n";
 *     }
 *
 * **{@see Iterator} works out one rule; this works out the set.** One
 * paragraph of §3.8.5.1 is the whole of it, and §3.8.5.2 repeats it word for
 * word:
 *
 * > The recurrence set is generated by considering the initial "DTSTART"
 * > property along with the "RRULE", "RDATE", and "EXDATE" properties
 * > contained within the recurring component. … **The final recurrence set is
 * > generated by gathering all of the start DATE-TIME values generated by any
 * > of the specified "RRULE" and "RDATE" properties, and then excluding any
 * > start DATE-TIME values specified by "EXDATE" properties.** This implies
 * > that start DATE-TIME values specified by "EXDATE" properties take
 * > precedence over those specified by inclusion properties (i.e., "RDATE"
 * > and "RRULE"). When duplicate instances are generated by the "RRULE" and
 * > "RDATE" properties, only one recurrence is considered. Duplicate
 * > instances are ignored.
 *
 * So: gather, then exclude, and count a moment once however many properties
 * named it. **Every one of those clauses is a sentence of specification**, and
 * the plural in "properties" is one of them — a component may carry several
 * `RDATE`s and several `EXDATE`s, and §3.8.5.3's "SHOULD NOT occur more than
 * once" about `RRULE` is advice to whoever writes one rather than leave to
 * ignore a second.
 *
 * ## `DTSTART` is in the set
 *
 * The paragraph looks as though it says both things. The set is generated "by
 * considering the initial 'DTSTART' property **along with**" the others, and
 * "The 'DTSTART' property defines the first instance in the recurrence set" —
 * but the sentence that says how the set is *gathered* names only `RRULE` and
 * `RDATE`.
 *
 * **The next paragraph settles it:** "The 'EXDATE' property can be used to
 * exclude the value specified in 'DTSTART'." Nothing can be excluded from a
 * set it was never in. So the start is an instance whether or not a rule
 * generates it, and a component with no `RRULE` and no `RDATE` has a
 * recurrence set of exactly one.
 *
 * And the rest of that sentence is about the property rather than the set:
 * "the original 'DTSTART' date MUST still be maintained … because the
 * original 'DTSTART' value has inherent usage dependencies by other
 * properties such as the 'RECURRENCE-ID'." The property stays where it is;
 * only the instance goes.
 *
 * ## `EXRULE` is read and never written
 *
 * §A.3, "Deprecated Features": "The 'EXRULE' property **can no longer be
 * specified in a component**", and §A.1 points at RFC 2445 §4.8.5.2 for what
 * it meant. R-RRULE-02 asks for it all the same, because data in the field
 * has it — so it is applied where it is found and never produced.
 *
 * **What it means here is read across from `EXDATE`**: the same "excluding
 * any start DATE-TIME values", by rule instead of by list. That is a reading
 * rather than a quotation, RFC 2445's own wording not being at hand, and it
 * is said here so that nobody takes it for the memo's.
 *
 * ## Why the instances are merged rather than collected
 *
 * A rule can repeat for ever — "the 'RRULE' is considered to repeat forever"
 * — so the set cannot be built and then sorted. Each part of it arrives in
 * order already: a rule's instances from {@see Iterator}, a property's dates
 * sorted once. **So the parts are merged**, the smallest head first, and the
 * exclusions walk along beside them. That keeps R-RRULE-04's lazy evaluation,
 * and the hard limit stays where it was: in the rules' own iterators.
 *
 * ## One moment, two writings
 *
 * A `DATE` and a `DATE-TIME` at midnight are the same moment spelled two
 * ways. The memo says "only one recurrence is considered" and does not say
 * which spelling — so the reading here is its own word order: the set is
 * gathered from "any of the specified 'RRULE' and 'RDATE' properties", in
 * that order, and a rule's writing of a moment is the one that stands.
 * {@see self::earliestIn()} is where that happens, and a test holds it.
 *
 * ## What a value cannot know
 *
 * The same as {@see Iterator}: a `TZID` is a parameter of the property and
 * this compares values, so the arithmetic is on the wall clock — which is
 * right for a floating set, for one in UTC, and for one with a `TZID` too,
 * "every Monday at nine" meaning nine o'clock on the wall.
 *
 * **Where a `TZID` names a zone it is handed in** ({@see Zone}) and reaches
 * every rule of the set, because §3.3.10 asks for an instance with no local
 * time to be passed over and not counted. **An `RDATE` is not passed over**:
 * that sentence is about what "recurrence rules may generate", and a date its
 * author wrote down stays in the set — a caller that asks the zone for its
 * moment is told null and can decide, which is a thing it can see.
 */
final class ExpandedSet
{
    /**
     * @param list<Rule> $rules Every `RRULE` of the component
     * @param list<Date|DateTime> $dates Every value of every `RDATE`
     * @param list<Rule> $exceptionRules Every `EXRULE`, which RFC 5545 removed
     * @param list<Date|DateTime> $exceptions Every value of every `EXDATE`
     * @param int $iterations The hard limit each rule is given (R-CAL-08)
     * @param Zone|null $zone The zone the values are written in, where a
     *                        `TZID` names one: it decides which instances
     *                        §3.3.10 passes over for having no local time
     */
    public function __construct(
        private readonly Date|DateTime $start,
        private readonly array $rules,
        private readonly array $dates,
        private readonly array $exceptionRules,
        private readonly array $exceptions,
        private readonly int $iterations = Iterator::ITERATIONS,
        private readonly ?Zone $zone = null,
    ) {
    }

    /**
     * The recurrence set a component describes.
     *
     * @param int $iterations The hard limit each rule is given (R-CAL-08)
     *
     * @throws ParseError If the component names no `DTSTART`, or one of its
     *                    recurrence properties cannot be read
     */
    public static function of(
        Component $component,
        int $iterations = Iterator::ITERATIONS,
        ?Zone $zone = null,
    ): self {
        $start = $component->property('DTSTART');

        if ($start === null) {
            throw new ParseError(
                'A recurrence set is computed from a DTSTART, and this component has none (RFC 5545 §3.8.5.1).',
            );
        }

        return new self(
            self::valueOf($start->parameter('VALUE')?->value(), $start->value()),
            self::rulesIn($component, 'RRULE'),
            self::datesIn($component, 'RDATE'),
            self::rulesIn($component, 'EXRULE'),
            self::datesIn($component, 'EXDATE'),
            $iterations,
            $zone,
        );
    }

    /**
     * The instances the set comes to, in order, one at a time.
     *
     * @throws TooManyIterations If one of the rules passes its hard limit
     *
     * @return Generator<int, Date|DateTime>
     */
    public function instances(): Generator
    {
        $included = $this->streamsOf($this->rules, [$this->start, ...$this->dates]);
        $excluded = $this->streamsOf($this->exceptionRules, $this->exceptions);

        // The loop ends where every stream has run out, which is what a set
        // of a `COUNT` or an `UNTIL` comes to; a set that repeats for ever
        // ends when the caller stops asking.
        while (($next = self::earliestIn($included)) !== null) {
            $moment = self::momentOf($next);

            // "When duplicate instances are generated by the RRULE and RDATE
            // properties, only one recurrence is considered." Every stream
            // standing on this moment moves past it, so a moment several
            // properties named is handed over once.
            self::movePast($included, $moment);

            if (!self::isExcluded($excluded, $moment)) {
                yield $next;
            }
        }
    }

    /**
     * One stream per rule and one for the dates, each in order.
     *
     * **PHP's own `Iterator` rather than this namespace's**, hence the
     * leading backslash: a rule's instances arrive from a generator and a
     * property's dates from an array, and the merge asks both the same three
     * questions.
     *
     * @param list<Rule> $rules
     * @param list<Date|DateTime> $dates
     *
     * @return list<\Iterator<int, Date|DateTime>>
     */
    private function streamsOf(array $rules, array $dates): array
    {
        $streams = [];

        foreach ($rules as $rule) {
            $streams[] = (new Iterator($rule, $this->start, $this->iterations, $this->zone))->instances();
        }

        $streams[] = new ArrayIterator(self::inOrder($dates));

        return $streams;
    }

    /**
     * A property's values sorted and each of them once.
     *
     * §3.1.1: "There is no significance to the order of values in a list", so
     * the set comes out in order however the component was written. A value's
     * own written form sorts chronologically, `date-time` being `date` with a
     * time appended.
     *
     * @param list<Date|DateTime> $dates
     *
     * @return list<Date|DateTime>
     */
    private static function inOrder(array $dates): array
    {
        $sorted = [];

        foreach ($dates as $date) {
            $sorted[$date->encode()] = $date;
        }

        ksort($sorted);

        return array_values($sorted);
    }

    /**
     * The earliest moment any stream is standing on, or null where they have
     * all run out.
     *
     * **Strictly earlier, so that the first stream wins a tie**, and that
     * decides a case the memo leaves open: a `DATE` and a `DATE-TIME` at
     * midnight are one moment written two ways, and "only one recurrence is
     * considered" without saying which writing. The reading is the memo's own
     * word order — the set is gathered from "any of the specified 'RRULE' and
     * 'RDATE' properties", in that order — so a rule's writing stands.
     *
     * @param list<\Iterator<int, Date|DateTime>> $streams
     */
    private static function earliestIn(array $streams): Date|DateTime|null
    {
        $earliest = null;

        foreach ($streams as $stream) {
            $head = $stream->valid() ? $stream->current() : null;

            if ($head !== null && ($earliest === null || self::momentOf($head) < self::momentOf($earliest))) {
                $earliest = $head;
            }
        }

        return $earliest;
    }

    /**
     * Moves every stream standing on a moment or before it past that moment.
     *
     * @param list<\Iterator<int, Date|DateTime>> $streams
     */
    private static function movePast(array $streams, DateTimeImmutable $moment): void
    {
        foreach ($streams as $stream) {
            while ($stream->valid() && self::momentOf($stream->current()) <= $moment) {
                $stream->next();
            }
        }
    }

    /**
     * Whether a moment is one the exclusions name.
     *
     * The exclusions arrive in order like everything else, so each one is
     * walked forward to this moment and asked. Nothing has to be remembered:
     * the instances are handed over in order, so an exclusion once passed is
     * passed for good.
     *
     * @param list<\Iterator<int, Date|DateTime>> $streams
     */
    private static function isExcluded(array $streams, DateTimeImmutable $moment): bool
    {
        $excluded = false;

        foreach ($streams as $stream) {
            while ($stream->valid() && self::momentOf($stream->current()) < $moment) {
                $stream->next();
            }

            // The head is now at this moment or past it, so standing on it
            // is the whole of being excluded by this stream — no equality to
            // compare, which two moments as objects would not answer anyway.
            if ($stream->valid() && self::momentOf($stream->current()) <= $moment) {
                $excluded = true;
            }
        }

        return $excluded;
    }

    /**
     * A value as a moment to compare with, in UTC because UTC has no summer
     * time — the same frame {@see Iterator} counts in.
     */
    private static function momentOf(Date|DateTime $value): DateTimeImmutable
    {
        return new DateTimeImmutable($value->encode(), new DateTimeZone('UTC'));
    }

    /**
     * Every rule a component carries under one name.
     *
     *
     * @throws ParseError If one of them is no `recur`
     *
     * @return list<Rule>
     */
    private static function rulesIn(Component $component, string $name): array
    {
        $rules = [];

        foreach ($component->properties($name) as $property) {
            $rules[] = Rule::decode($property->value());
        }

        return $rules;
    }

    /**
     * Every value of every property a component carries under one name.
     *
     * §3.8.5.1 and §3.8.5.2 both say "the list of DATE-TIME values", and
     * §3.1.1 writes a list of values in one property separated by commas. A
     * `PERIOD` carries a solidus rather than a comma, so one split serves all
     * three value types.
     *
     *
     * @throws ParseError If one of them is no date, date-time or period
     *
     * @return list<Date|DateTime>
     */
    private static function datesIn(Component $component, string $name): array
    {
        $dates = [];

        foreach ($component->properties($name) as $property) {
            $type = $property->parameter('VALUE')?->value();

            foreach (explode(',', $property->value()) as $raw) {
                $dates[] = self::valueOf($type, $raw);
            }
        }

        return $dates;
    }

    /**
     * One value of a recurrence property, the `VALUE` parameter saying which
     * kind it is.
     *
     * "The default value type for this property is DATE-TIME. The value type
     * can be set to DATE" (§3.8.5.1), "or PERIOD" (§3.8.5.2). **Compared
     * without regard to case**, §3.1 saying that "property parameter values
     * are case-insensitive".
     *
     * **A period contributes its start and nothing else**, because that is
     * what the memo gathers: "all of the **start** DATE-TIME values". How
     * long an instance lasts is a property of the instance rather than of the
     * set, and `DTEND`/`DURATION` are where a component says so.
     *
     * @throws ParseError If the raw value is none of the three
     */
    private static function valueOf(?string $type, string $raw): Date|DateTime
    {
        if ($type !== null && strcasecmp($type, 'DATE') === 0) {
            return Date::decode($raw);
        }

        if ($type !== null && strcasecmp($type, 'PERIOD') === 0) {
            return Period::decode($raw)->start();
        }

        return DateTime::decode($raw);
    }
}
