<?php

/*
 * This file is part of davServices.
 *
 * (c) Felix Böck <https://dav.services>
 *
 * Licensed under the Apache License, Version 2.0.
 * For the full copyright and license information, see the LICENSE file.
 */

declare(strict_types=1);

namespace DavServices\VObject\Recur;

use RuntimeException;

/**
 * A recurrence rule carries a part this library cannot yet work out.
 *
 * **Not a parse error.** The rule is well formed and {@see Rule} read it
 * without difficulty; what is missing is here, in the expansion. So the data
 * is valid and `CALDAV:valid-calendar-data` would be the wrong answer at the
 * protocol edge — this is a limit of the implementation, not of the file.
 *
 * ## Why refusing rather than leaving the part out
 *
 * **RFC 5545 §3.3.10 licenses ignoring a rule part exactly once, and says so
 * by name:** "These rule parts MUST be ignored in RECUR value that violate
 * the above requirement (e.g., generated by applications that pre-date this
 * revision of iCalendar)" — of `BYSECOND`, `BYMINUTE` and `BYHOUR` beside a
 * `DTSTART` of type `DATE`, and nowhere else.
 *
 * Everywhere else the memo says the parts **are applied**: "the BYxxx rule
 * parts are applied to the current set of evaluated occurrences in the
 * following order". A set that quietly left one out would be a set the memo
 * does not define — and an appointment at the wrong time is worse than an
 * appointment that failed to arrive.
 *
 * ## What it covers, and for how long
 *
 * `BYSETPOS` alone, since P4-08b. **The memo sets it apart itself**, twice
 * over: it evaluates it after every other part — "BYMONTH, BYWEEKNO,
 * BYYEARDAY, BYMONTHDAY, BYDAY, BYHOUR, BYMINUTE, BYSECOND and BYSETPOS; then
 * COUNT and UNTIL are evaluated" — and it is the one part that needs a whole
 * period at once: "BYSETPOS operates on a set of recurrence instances in one
 * interval of the recurrence rule." {@see ByRules} hands a period over one
 * candidate at a time, so that is a stage of its own and P4-08c's subject.
 *
 * **This class goes when it arrives.** It is a statement about today's
 * library rather than about the format.
 */
final class NotExpanded extends RuntimeException
{
    /**
     * @param non-empty-string $part The rule part, as §3.3.10 names it
     */
    public function __construct(string $part)
    {
        parent::__construct(sprintf(
            'This library does not yet work out a recurrence rule with a %s part.',
            $part,
        ));
    }
}
