<?php

/*
 * This file is part of davServices.
 *
 * (c) Felix Böck <https://dav.services>
 *
 * Licensed under the Apache License, Version 2.0.
 * For the full copyright and license information, see the LICENSE file.
 */

declare(strict_types=1);

namespace DavServices\VObject\Recur;

use ArrayIterator;
use DateTimeImmutable;
use DateTimeZone;
use DavServices\VObject\Component;
use DavServices\VObject\ParseError;
use DavServices\VObject\Property;
use DavServices\VObject\Value\Date;
use DavServices\VObject\Value\DateTime;
use Generator;

/**
 * The instances of one calendar object, overrides applied (RFC 5545 §3.8.4.4,
 * RFC 4791 §4.1, R-RRULE-03).
 *
 *     foreach (ObjectSet::of($calendar, $uid)->instances() as $instance) {
 *         echo $instance->start()->encode(), ' ', $instance->recurrenceId()->encode(), "\n";
 *     }
 *
 * **{@see ExpandedSet} answers when a component recurs; this answers what the
 * instances of an object are, and which component describes each.** RFC 4791
 * §4.1 gives the two words: the "**master**" recurring component, which
 * "defines the recurrence 'set' and does not contain any RECURRENCE-ID
 * property", and the "**overridden**" instances, which "modify the behavior
 * of a regular instance, and thus include a RECURRENCE-ID property". They
 * share a `UID`, and "Calendar components with the same UID property value …
 * MUST be contained in the same calendar object resource" — which is why a
 * `UID` is what this is asked for.
 *
 * ## An identifier points at where an instance was
 *
 * §3.8.4.4: "The property value is the **original** value of the 'DTSTART'
 * property of the recurrence instance." The memo says it twice, because it is
 * the thing to get wrong: "if the intent is to change a Friday meeting to
 * Thursday, the DATE-TIME is still set to the original Friday meeting."
 *
 * So the set is walked **in identifier order**, which is also what the memo
 * reasons in: "Subsequent instances are determined by their 'RECURRENCE-ID'
 * value and not their current scheduled start time." A moved instance can
 * overtake its neighbour, and nothing in the memo sorts the set again
 * afterwards — nor could anything, a series that repeats for ever not
 * fitting in a sort.
 *
 * ## `RANGE` is a shift
 *
 * §3.2.13: "If this parameter is not specified on an allowed property, then
 * the **default range is the single instance** specified by the recurrence
 * identifier value of the property." Where it is specified, §3.8.4.4 says
 * what it does:
 *
 * > When the given recurrence instance is rescheduled, all subsequent
 * > instances are also rescheduled **by the same time difference**. For
 * > instance, if the given recurrence instance is rescheduled to start 2
 * > hours later, then all subsequent instances are also rescheduled 2 hours
 * > later.
 *
 * And two sentences keep that from running away. "Subsequent instances
 * defined in separate components are not impacted by the given recurrence
 * instance" — an instance with a component of its own keeps its own start.
 * And the identifiers, not the starts, are what a later override is matched
 * by, so a shift cannot hide one.
 *
 * **`THISANDPRIOR` is not read.** §3.2.13's grammar admits one value —
 * `rangeparam = "RANGE" "=" "THISANDFUTURE"` — and says of the other that it
 * "is deprecated by this revision of iCalendar and MUST NOT be generated by
 * applications"; §A.3 that it "can no longer be used with the 'RANGE'
 * parameter". Unlike `EXRULE`, which R-RRULE-02 asks for by name, nothing
 * asks for this one, so it is refused rather than guessed at.
 *
 * ## What the memo leaves open, and what is read into it
 *
 * **An override whose identifier names no instance of the master.** RFC 4791
 * §4.1 says an object may "just contain components that represent
 * 'overridden' instances … without also including the 'master' recurring
 * component", so an override is an instance in its own right. Read the same
 * way where a master is there but does not generate that moment: the instance
 * is in the set, in its identifier's place. **That is a reading**, and it is
 * marked as one.
 *
 * ## What waits for another chunk
 *
 * §3.8.4.4 says one more thing about a range: "Similarly, if the duration of
 * the given recurrence instance is modified, then all subsequent instances
 * are also modified to have this same duration." **A duration is not part of
 * the recurrence set**, which is a set of starts, and where a component says
 * how long an instance lasts — `DTEND`, `DURATION`, `DUE` — is P6-05's
 * subject together with `time-range`. The sentence is quoted here so that it
 * is not lost.
 */
final class ObjectSet
{
    /**
     * @param Component|null $master The component that defines the series, or
     *                               null for an object of overrides alone
     * @param list<Instance> $overrides The overriding components, in
     *                                  identifier order
     * @param int $iterations The hard limit the series is given (R-CAL-08)
     */
    private function __construct(
        private readonly ?Component $master,
        private readonly array $overrides,
        private readonly int $iterations,
    ) {
    }

    /**
     * The instances of the series a `UID` names within an object.
     *
     * @param int $iterations The hard limit the series is given (R-CAL-08)
     *
     * @throws ParseError If the object carries no such series, more than one
     *                    master for it, or a component this cannot read
     */
    public static function of(Component $object, string $uid, int $iterations = Iterator::ITERATIONS): self
    {
        $master = null;
        $overrides = [];

        foreach ($object->components() as $component) {
            if ($component->property('UID')?->value() !== $uid) {
                continue;
            }

            $identifier = $component->property('RECURRENCE-ID');

            if ($identifier === null) {
                $master = self::theOnlyMaster($master, $component, $uid);

                continue;
            }

            $overrides[] = self::overrideOf($component, $identifier);
        }

        if ($master === null && $overrides === []) {
            throw new ParseError(sprintf('No component of this object carries the UID "%s".', $uid));
        }

        if ($master !== null) {
            self::refuseAMixtureOfValueTypes($master, $overrides);
        }

        return new self($master, self::inIdentifierOrder($overrides), $iterations);
    }

    /**
     * The instances the object comes to, in identifier order, one at a time.
     *
     * @throws TooManyIterations If the series passes its hard limit
     *
     * @return Generator<int, Instance>
     */
    public function instances(): Generator
    {
        $master = $this->master;

        if ($master === null) {
            // RFC 4791 §4.1: an object may "just contain components that
            // represent 'overridden' instances". With no series to generate
            // anything, every instance brings its own component — and a range
            // reaches nothing, "subsequent instances defined in separate
            // components" not being impacted by it.
            yield from $this->overrides;

            return;
        }

        $identifiers = $this->identifierStreams($master);
        $shift = 0;

        while (($identifier = self::earliestIn($identifiers)) !== null) {
            self::movePast($identifiers, self::momentOf($identifier));

            $override = $this->overrideFor($identifier);

            if ($override === null) {
                yield new Instance($identifier, self::shiftedBy($identifier, $shift), $master);

                continue;
            }

            yield $override;

            // "the default range is the single instance specified by the
            // recurrence identifier value of the property" — so a shift is
            // only in effect where this one asked for it, and a later range
            // takes over from an earlier.
            if (self::isThisAndFuture($override->component())) {
                $shift = self::momentOf($override->start())->getTimestamp()
                    - self::momentOf($override->recurrenceId())->getTimestamp();
            }
        }
    }

    /**
     * The series' own identifiers and the overrides', each stream in order.
     *
     * **An override's identifier is a stream of its own** rather than only a
     * lookup, because of the reading above: an identifier the series does not
     * generate is an instance all the same, and it takes its place here.
     *
     * @return list<\Iterator<int, Date|DateTime>>
     */
    private function identifierStreams(Component $master): array
    {
        $identifiers = [];

        foreach ($this->overrides as $override) {
            $identifiers[] = $override->recurrenceId();
        }

        return [
            ExpandedSet::of($master, $this->iterations)->instances(),
            new ArrayIterator($identifiers),
        ];
    }

    /**
     * The override that stands for an identifier, or null where the series
     * answers for it itself.
     *
     * A handful of overrides is all a component ever has, so they are looked
     * through rather than indexed — and the comparison is on the written
     * form, two values being equal when they are written the same way.
     */
    private function overrideFor(Date|DateTime $identifier): ?Instance
    {
        foreach ($this->overrides as $override) {
            if ($override->recurrenceId()->encode() === $identifier->encode()) {
                return $override;
            }
        }

        return null;
    }

    /**
     * One overriding component, read as the instance it stands for.
     *
     * @throws ParseError If its `RANGE` is not the one §3.2.13 admits, or it
     *                    carries no `DTSTART`
     */
    private static function overrideOf(Component $component, Property $identifier): Instance
    {
        $range = $identifier->parameter('RANGE')?->value();

        // §3.2.13: `rangeparam = "RANGE" "=" "THISANDFUTURE"`, and §3.1 makes
        // "property parameter values" case-insensitive.
        if ($range !== null && strcasecmp($range, 'THISANDFUTURE') !== 0) {
            throw new ParseError(sprintf(
                '"%s" is no RANGE; RFC 5545 §3.2.13 admits THISANDFUTURE and nothing else.',
                $range,
            ));
        }

        $start = $component->property('DTSTART');

        if ($start === null) {
            throw new ParseError(
                'An overriding component says where its instance begins, and this one has no DTSTART.',
            );
        }

        return new Instance(self::dateOf($identifier), self::dateOf($start), $component);
    }

    /**
     * Whether an overriding component's range reaches the instances after it.
     */
    private static function isThisAndFuture(Component $component): bool
    {
        $range = $component->property('RECURRENCE-ID')?->parameter('RANGE')?->value();

        return $range !== null && strcasecmp($range, 'THISANDFUTURE') === 0;
    }

    /**
     * The one component of a series that defines it.
     *
     * RFC 4791 §4.1 knows one "master recurring component" per resource, and
     * which of two would define the series is nothing the memo answers.
     *
     * @throws ParseError If there is a second
     */
    private static function theOnlyMaster(?Component $master, Component $found, string $uid): Component
    {
        if ($master !== null) {
            throw new ParseError(sprintf(
                'The UID "%s" has one master component in an object, and this one has two (RFC 4791 §4.1).',
                $uid,
            ));
        }

        return $found;
    }

    /**
     * §3.8.4.4: "This property MUST have the same value type as the 'DTSTART'
     * property contained within the recurring component."
     *
     * @param list<Instance> $overrides
     *
     * @throws ParseError If one of them is of the other kind
     */
    private static function refuseAMixtureOfValueTypes(Component $master, array $overrides): void
    {
        $start = $master->property('DTSTART');
        $days = $start !== null && self::dateOf($start) instanceof Date;

        foreach ($overrides as $override) {
            if ($override->recurrenceId() instanceof Date !== $days) {
                throw new ParseError(
                    'A RECURRENCE-ID has the same value type as the DTSTART it identifies (RFC 5545 §3.8.4.4).',
                );
            }
        }
    }

    /**
     * The overrides sorted by the identifiers that name them.
     *
     * A value's own written form sorts chronologically, `date-time` being
     * `date` with a time appended.
     *
     * @param list<Instance> $overrides
     *
     * @return list<Instance>
     */
    private static function inIdentifierOrder(array $overrides): array
    {
        $sorted = [];

        foreach ($overrides as $override) {
            $sorted[$override->recurrenceId()->encode()] = $override;
        }

        ksort($sorted);

        return array_values($sorted);
    }

    /**
     * The earliest identifier any stream is standing on, or null where they
     * have all run out.
     *
     * Strictly earlier, so that the series' own identifier wins a tie over an
     * override's — they are the same moment, and the series' is the one the
     * memo calls original.
     *
     * @param list<\Iterator<int, Date|DateTime>> $streams
     */
    private static function earliestIn(array $streams): Date|DateTime|null
    {
        $earliest = null;

        foreach ($streams as $stream) {
            $head = $stream->valid() ? $stream->current() : null;

            if ($head !== null && ($earliest === null || self::momentOf($head) < self::momentOf($earliest))) {
                $earliest = $head;
            }
        }

        return $earliest;
    }

    /**
     * Moves every stream standing on a moment or before it past that moment,
     * so that an identifier both the series and an override name is walked
     * once.
     *
     * @param list<\Iterator<int, Date|DateTime>> $streams
     */
    private static function movePast(array $streams, DateTimeImmutable $moment): void
    {
        foreach ($streams as $stream) {
            while ($stream->valid() && self::momentOf($stream->current()) <= $moment) {
                $stream->next();
            }
        }
    }

    /**
     * An identifier moved by the shift a range put in effect, keeping the kind
     * of value it is.
     */
    private static function shiftedBy(Date|DateTime $identifier, int $seconds): Date|DateTime
    {
        $moment = self::momentOf($identifier);
        $shifted = $moment->setTimestamp($moment->getTimestamp() + $seconds);

        if ($identifier instanceof Date) {
            return Date::decode($shifted->format('Ymd'));
        }

        return DateTime::decode($shifted->format('Ymd\THis') . ($identifier->isUtc() ? 'Z' : ''));
    }

    /**
     * One value of a property that names a day or a moment.
     *
     * §3.8.4.4 of `RECURRENCE-ID` and §3.8.2.4 of `DTSTART` say the same
     * thing: "The default value type is DATE-TIME. The value type can be set
     * to a DATE value type." Neither admits a `PERIOD`, which is where this
     * differs from {@see ExpandedSet}'s reading of an `RDATE`. §3.1 makes the
     * parameter's value case-insensitive.
     *
     * @throws ParseError If the value is neither
     */
    private static function dateOf(Property $property): Date|DateTime
    {
        $type = $property->parameter('VALUE')?->value();

        if ($type !== null && strcasecmp($type, 'DATE') === 0) {
            return Date::decode($property->value());
        }

        return DateTime::decode($property->value());
    }

    /**
     * A value as a moment to compare with, in UTC because UTC has no summer
     * time — the same frame {@see Iterator} counts in.
     */
    private static function momentOf(Date|DateTime $value): DateTimeImmutable
    {
        return new DateTimeImmutable($value->encode(), new DateTimeZone('UTC'));
    }
}
