<?php

/*
 * This file is part of davServices.
 *
 * (c) Felix Böck <https://dav.services>
 *
 * Licensed under the Apache License, Version 2.0.
 * For the full copyright and license information, see the LICENSE file.
 */

declare(strict_types=1);

namespace DavServices\Tests\Unit\VObject\Recur;

use DavServices\VObject\Component;
use DavServices\VObject\Parameter;
use DavServices\VObject\ParseError;
use DavServices\VObject\Property;
use DavServices\VObject\Recur\ExpandedSet;
use DavServices\VObject\Recur\Iterator;
use DavServices\VObject\Recur\TooManyIterations;
use DavServices\VObject\Value\Period;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * Test list for the recurrence set of one component. RFC 5545 §3.8.5.
 * R-RRULE-02.
 *
 * **One paragraph of §3.8.5.1 is the whole algorithm**, and it is given twice
 * over — §3.8.5.2 repeats it word for word, which is a fair sign of how much
 * weight it carries:
 *
 * > The recurrence set is generated by considering the initial "DTSTART"
 * > property along with the "RRULE", "RDATE", and "EXDATE" properties
 * > contained within the recurring component. … **The final recurrence set is
 * > generated by gathering all of the start DATE-TIME values generated by any
 * > of the specified "RRULE" and "RDATE" properties, and then excluding any
 * > start DATE-TIME values specified by "EXDATE" properties.** This implies
 * > that start DATE-TIME values specified by "EXDATE" properties take
 * > precedence over those specified by inclusion properties (i.e., "RDATE"
 * > and "RRULE"). When duplicate instances are generated by the "RRULE" and
 * > "RDATE" properties, only one recurrence is considered. Duplicate
 * > instances are ignored.
 *
 * Every sentence of it is a test below, the precedence and the duplicates
 * included.
 *
 * ## Is `DTSTART` in the set?
 *
 * The paragraph says two things that look like they disagree. The set is
 * generated "by considering the initial 'DTSTART' property **along with**" the
 * others, and "The 'DTSTART' property defines the first instance in the
 * recurrence set" — but the sentence that says how the final set is *gathered*
 * names only `RRULE` and `RDATE`.
 *
 * **The next paragraph settles it**: "The 'EXDATE' property can be used to
 * exclude the value specified in 'DTSTART'." Nothing can be excluded from a
 * set it was never in. So `DTSTART` is an instance, with or without a rule to
 * generate it — and a component with no `RRULE` and no `RDATE` has a
 * recurrence set of exactly one.
 *
 * And the other half of that sentence is a caution rather than a rule about
 * the set: "the original 'DTSTART' date MUST still be maintained … because
 * the original 'DTSTART' value has inherent usage dependencies by other
 * properties such as the 'RECURRENCE-ID'." The property stays; only the
 * instance goes.
 *
 * ## `EXRULE` is read and never written
 *
 * §A.3, "Deprecated Features": "The 'EXRULE' property **can no longer be
 * specified in a component**." §A.1 lists it as deprecated and points at RFC
 * 2445 §4.8.5.2 for what it meant. R-RRULE-02 asks for it all the same,
 * because data in the field has it — so it is applied where it is found and
 * never produced, and **what it means here is read across from `EXDATE`**:
 * the same "excluding any start DATE-TIME values", by rule instead of by
 * list. That is a reading, RFC 2445's own wording not being at hand, and it is
 * marked as one in the source.
 */
#[CoversClass(ExpandedSet::class)]
// Driven by this test as well; ci.yml says why naming them matters.
#[CoversClass(Iterator::class)]
#[CoversClass(Period::class)]
final class ExpandedSetTest extends TestCase
{
    /**
     * **A component with neither rule nor date has a set of one.** "The
     * 'DTSTART' property defines the first instance in the recurrence set."
     */
    public function testAComponentWithoutRuleOrDateIsItsOwnWholeSet(): void
    {
        self::assertSame(['19970902T090000'], self::expand([
            ['DTSTART', '19970902T090000'],
        ]));
    }

    /**
     * **"the recurrence instances are defined by the union of occurrences
     * defined by both the 'RDATE' and 'RRULE'"** (§3.8.5.2), and the union
     * comes out in order.
     */
    public function testARuleAndADateMakeAUnion(): void
    {
        self::assertSame(
            ['19970902T090000', '19970903T090000', '19970904T090000', '19970910T090000'],
            self::expand([
                ['DTSTART', '19970902T090000'],
                ['RRULE', 'FREQ=DAILY;COUNT=3'],
                ['RDATE', '19970910T090000'],
            ]),
        );
    }

    /**
     * **Dates without a rule**, and in order however they were written —
     * §3.1.1: "There is no significance to the order of values in a list."
     */
    public function testDatesWithoutARuleComeOutInOrder(): void
    {
        self::assertSame(
            ['19970902T090000', '19970903T090000', '19970905T090000'],
            self::expand([
                ['DTSTART', '19970902T090000'],
                ['RDATE', '19970905T090000,19970903T090000'],
            ]),
        );
    }

    /**
     * **"then excluding any start DATE-TIME values specified by 'EXDATE'
     * properties".**
     */
    public function testAnExceptionTakesAnInstanceOutOfTheSet(): void
    {
        self::assertSame(
            ['19970902T090000', '19970903T090000', '19970905T090000', '19970906T090000'],
            self::expand([
                ['DTSTART', '19970902T090000'],
                ['RRULE', 'FREQ=DAILY;COUNT=5'],
                ['EXDATE', '19970904T090000'],
            ]),
        );
    }

    /**
     * **Does `COUNT` count what the rule produced or what survived the
     * exclusion?** R-RRULE-05 names the pair as an edge case, and the memo
     * answers it twice over.
     *
     * §3.3.10 evaluates `COUNT` **inside the rule**: "the BYxxx rule parts
     * are applied … in the following order: … and BYSETPOS; **then COUNT and
     * UNTIL are evaluated**." And §3.8.5.1 puts the exclusion **after** the
     * rules have had their say: "gathering all of the start DATE-TIME values
     * generated by any of the specified 'RRULE' and 'RDATE' properties, and
     * **then** excluding any start DATE-TIME values specified by 'EXDATE'
     * properties."
     *
     * So the rule counts to five and the exclusion takes one of those five
     * away: **four instances, not five.** Worth saying outright, because the
     * other reading is the intuitive one and nothing in the code would stop
     * somebody from "fixing" it.
     */
    public function testACountCountsBeforeAnExceptionTakesAnythingAway(): void
    {
        self::assertSame(
            ['19970902T090000', '19970903T090000', '19970905T090000'],
            self::expand([
                ['DTSTART', '19970902T090000'],
                ['RRULE', 'FREQ=DAILY;COUNT=4'],
                ['EXDATE', '19970904T090000'],
            ]),
        );
    }

    /**
     * **"EXDATE properties take precedence over those specified by inclusion
     * properties (i.e., 'RDATE' and 'RRULE')."** The same moment named by
     * both an `RDATE` and an `EXDATE` is not in the set.
     */
    public function testAnExceptionTakesPrecedenceOverADate(): void
    {
        self::assertSame(
            ['19970902T090000'],
            self::expand([
                ['DTSTART', '19970902T090000'],
                ['RDATE', '19970910T090000'],
                ['EXDATE', '19970910T090000'],
            ]),
        );
    }

    /**
     * **"The 'EXDATE' property can be used to exclude the value specified in
     * 'DTSTART'."** The first instance goes and the rest of the rule stays.
     */
    public function testAnExceptionCanExcludeTheStartItself(): void
    {
        self::assertSame(
            ['19970903T090000', '19970904T090000'],
            self::expand([
                ['DTSTART', '19970902T090000'],
                ['RRULE', 'FREQ=DAILY;COUNT=3'],
                ['EXDATE', '19970902T090000'],
            ]),
        );
    }

    /**
     * **"When duplicate instances are generated by the 'RRULE' and 'RDATE'
     * properties, only one recurrence is considered."**
     */
    public function testAMomentNamedTwiceIsOneInstance(): void
    {
        self::assertSame(
            ['19970902T090000', '19970903T090000', '19970904T090000'],
            self::expand([
                ['DTSTART', '19970902T090000'],
                ['RRULE', 'FREQ=DAILY;COUNT=3'],
                ['RDATE', '19970903T090000'],
            ]),
        );
    }

    /**
     * **The properties are plural in the memo's own sentence** — "any of the
     * specified 'RRULE' and 'RDATE' properties", "excluding … values
     * specified by 'EXDATE' properties" — so more than one of each is read.
     */
    public function testSeveralDateAndExceptionPropertiesAreAllRead(): void
    {
        self::assertSame(
            ['19970902T090000', '19970905T090000', '19970907T090000'],
            self::expand([
                ['DTSTART', '19970902T090000'],
                ['RDATE', '19970905T090000'],
                ['RDATE', '19970906T090000'],
                ['RDATE', '19970907T090000'],
                ['EXDATE', '19970906T090000'],
            ]),
        );
    }

    /**
     * **Several rules, likewise.** §3.8.5.3 says an `RRULE` "SHOULD NOT occur
     * more than once", which is advice to whoever writes one — and the
     * sentence that builds the set says "any of the specified 'RRULE' …
     * properties", which is an instruction to whoever reads them.
     */
    public function testSeveralRulesAreAllRead(): void
    {
        self::assertSame(
            ['19970902T090000', '19970903T090000', '19970909T090000'],
            self::expand([
                ['DTSTART', '19970902T090000'],
                ['RRULE', 'FREQ=DAILY;COUNT=2'],
                ['RRULE', 'FREQ=WEEKLY;COUNT=2'],
            ]),
        );
    }

    /**
     * **`RDATE` and `EXDATE` as dates**: "The value type can be set to DATE"
     * (§3.8.5.1) and "to DATE or PERIOD" (§3.8.5.2).
     *
     * @param list<array{string, string, string|null}> $properties
     * @param list<string> $instances
     */
    #[DataProvider('theOtherValueTypes')]
    public function testTheOtherValueTypesAreRead(array $properties, array $instances): void
    {
        self::assertSame($instances, self::expand($properties));
    }

    /**
     * @return iterable<string, array{list<array{string, string, string|null}>, list<string>}>
     */
    public static function theOtherValueTypes(): iterable
    {
        yield 'a date, where the start is a date too' => [
            [
                ['DTSTART', '19970902', 'DATE'],
                ['RDATE', '19970905', 'DATE'],
            ],
            ['19970902', '19970905'],
        ];

        // §3.1: "All names of properties, property parameters, enumerated
        // property values, and property parameter values are
        // case-insensitive."
        yield 'a date whose VALUE parameter is written in lower case' => [
            [
                ['DTSTART', '19970902', 'date'],
                ['RDATE', '19970905', 'Date'],
            ],
            ['19970902', '19970905'],
        ];

        yield 'a period whose VALUE parameter is written in lower case' => [
            [
                ['DTSTART', '19970902T090000', null],
                ['RDATE', '19970910T090000/PT2H', 'period'],
            ],
            ['19970902T090000', '19970910T090000'],
        ];

        yield 'an exception given as a date' => [
            [
                ['DTSTART', '19970902', 'DATE'],
                ['RRULE', 'FREQ=DAILY;COUNT=3', null],
                ['EXDATE', '19970903', 'DATE'],
            ],
            ['19970902', '19970904'],
        ];

        // §3.8.5.1 gathers "the start DATE-TIME values", so a period
        // contributes its start; its length belongs to the instance rather
        // than to the set.
        yield 'a period, of which the set takes the start' => [
            [
                ['DTSTART', '19970902T090000', null],
                ['RDATE', '19970910T090000/PT2H', 'PERIOD'],
            ],
            ['19970902T090000', '19970910T090000'],
        ];

        yield 'a period written with an end rather than a length' => [
            [
                ['DTSTART', '19970902T090000', null],
                ['RDATE', '19970910T090000/19970910T110000', 'PERIOD'],
            ],
            ['19970902T090000', '19970910T090000'],
        ];
    }

    /**
     * **One moment, two writings — and the memo does not say which is handed
     * over.** A `DATE` and a `DATE-TIME` at midnight are the same moment;
     * "only one recurrence is considered", but not which spelling of it.
     *
     * **The reading here is the memo's own word order**: the set is gathered
     * from "any of the specified 'RRULE' and 'RDATE' properties", in that
     * order, so a rule's writing of a moment is the one that stands. Said
     * here rather than left to chance, because a reader who met the other
     * answer would have no way of telling whether it was meant.
     */
    public function testWhereTwoPropertiesWriteOneMomentTheRulesWritingStands(): void
    {
        self::assertSame(
            ['19970902', '19970903'],
            self::expand([
                ['DTSTART', '19970902', 'DATE'],
                ['RRULE', 'FREQ=DAILY;COUNT=2', null],
                ['RDATE', '19970903T000000', 'DATE-TIME'],
            ]),
        );
    }

    /**
     * **`EXRULE`, which RFC 5545 removed and data in the field still has.**
     * Every other day out of every day leaves the days in between.
     */
    public function testALegacyExceptionRuleExcludesByRule(): void
    {
        self::assertSame(
            ['19970903T090000', '19970905T090000', '19970907T090000'],
            self::expand([
                ['DTSTART', '19970902T090000'],
                ['RRULE', 'FREQ=DAILY;COUNT=6'],
                ['EXRULE', 'FREQ=DAILY;INTERVAL=2;COUNT=3'],
            ]),
        );
    }

    /**
     * **A rule that repeats for ever is still handed over one at a time**
     * (R-RRULE-04's lazy evaluation), and the dates beside it do not change
     * that.
     */
    public function testASetThatNeverEndsIsStillTakenOneAtATime(): void
    {
        self::assertSame(
            ['19970902T090000', '19970903T090000', '19970904T090000', '19970905T090000'],
            self::expand([
                ['DTSTART', '19970902T090000'],
                ['RRULE', 'FREQ=DAILY'],
                ['RDATE', '19970905T090000'],
            ], 4),
        );
    }

    /**
     * **And the hard limit still bounds the work** (R-RRULE-04). A rule whose
     * every instance is excluded has nothing to hand over, and the refusal
     * comes from the limit rather than from a hang.
     */
    public function testTheHardLimitStillBoundsTheWork(): void
    {
        $this->expectException(TooManyIterations::class);

        self::expand([
            ['DTSTART', '19970902T090000'],
            ['RRULE', 'FREQ=DAILY'],
            ['EXRULE', 'FREQ=DAILY'],
        ], 5, 20);
    }

    /**
     * **A component with no `DTSTART` has no recurrence set to speak of.**
     * §3.8.5.1 computes the set "by considering the initial 'DTSTART'
     * property", so without one there is nothing to compute from — and
     * §3.6.1 requires the property of an event anyway.
     */
    public function testAComponentWithoutAStartIsRefused(): void
    {
        $this->expectException(ParseError::class);
        $this->expectExceptionMessage('DTSTART');

        self::expand([['RRULE', 'FREQ=DAILY;COUNT=3']]);
    }

    /**
     * The recurrence set of a component built from the properties given, as
     * the instances are written.
     *
     * @param list<array{string, string}|array{string, string, string|null}> $properties
     *
     * @return list<string>
     */
    private static function expand(array $properties, int $take = 500, ?int $iterations = null): array
    {
        $event = new Component('VEVENT');

        foreach ($properties as $property) {
            $added = new Property($property[0], $property[1]);
            $type = $property[2] ?? null;

            if ($type !== null) {
                $added->add(new Parameter('VALUE', [$type]));
            }

            $event->add($added);
        }

        $set = ExpandedSet::of($event, $iterations ?? 10000);
        $instances = [];

        foreach ($set->instances() as $instance) {
            $instances[] = $instance->encode();

            if (count($instances) === $take) {
                break;
            }
        }

        return $instances;
    }
}
