<?php

/*
 * This file is part of davServices.
 *
 * (c) Felix Böck <https://dav.services>
 *
 * Licensed under the Apache License, Version 2.0.
 * For the full copyright and license information, see the LICENSE file.
 */

declare(strict_types=1);

namespace DavServices\Tests\Unit\VObject\Recur;

use DavServices\VObject\Component;
use DavServices\VObject\Property;
use DavServices\VObject\Recur\ByRules;
use DavServices\VObject\Recur\ExpandedSet;
use DavServices\VObject\Recur\Iterator;
use DavServices\VObject\Recur\Weeks;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * The published vector set, run against the expansion. R-RRULE-06.
 *
 * **R-RRULE-06 asks for validation against a public test vector set**, and
 * there is one public, normative set for recurrence rules: the examples RFC
 * 5545 §3.8.5.3 publishes with its own answers. Thirty-nine of them, forty-two
 * rules — three examples give two rules for one answer, which makes the pair
 * a test of the specification rather than of a rule.
 *
 * They live in `tests/vectors/rfc5545-recurrence.json`, one entry per rule,
 * each carrying **the memo's answer verbatim** beside the instances it was
 * transcribed into. That is what makes the transcription auditable: a reader
 * with the RFC open compares `published` against the text, and `instances`
 * against `published`. Nothing here is generated by the code under test.
 *
 * ## What the vectors are checked against
 *
 * Each vector is expanded as a component — `DTSTART`, the rule, and any
 * `EXDATE` — through {@see ExpandedSet}, which is what a recurrence set is.
 * **One of the memo's examples requires it**: "Every Friday the 13th,
 * forever" carries an `EXDATE` for its own `DTSTART`, which is §3.8.5.1's
 * "The 'EXDATE' property can be used to exclude the value specified in
 * 'DTSTART'" applied by the memo itself.
 *
 * Where a rule bounds itself with `COUNT` or `UNTIL`, one more instance than
 * the memo lists is asked for, so that a set that runs on too long fails
 * here. Where it repeats for ever, the published prefix is what there is to
 * check.
 *
 * ## The one thing the vectors cannot check yet
 *
 * **Every example carries `TZID=America/New_York`**, and a `TZID` is a
 * parameter of the property rather than part of the value — so the expansion
 * works on the wall clock, as {@see Iterator} sets out. For these examples
 * that is exactly right: the memo's answers are themselves wall-clock times,
 * and it marks the summer-time changes only by writing `EDT` or `EST` beside
 * them. The instant each one names needs the zone, and that is P4-11's.
 */
#[CoversClass(ExpandedSet::class)]
#[CoversClass(Iterator::class)]
#[CoversClass(ByRules::class)]
#[CoversClass(Weeks::class)]
final class VectorsTest extends TestCase
{
    /**
     * **Every rule the memo publishes, against the answer it publishes.**
     *
     * @param non-empty-string $dtstart
     * @param non-empty-string $rule
     * @param list<string> $exdate
     * @param list<string> $instances
     */
    #[DataProvider('theVectors')]
    public function testAPublishedRuleComesToItsPublishedAnswer(
        string $dtstart,
        string $rule,
        array $exdate,
        array $instances,
    ): void {
        // A rule that bounds itself is asked for one more than the memo
        // lists, so that a set running on too long is a failure here.
        $bounded = str_contains($rule, 'COUNT=') || str_contains($rule, 'UNTIL=');

        self::assertSame(
            $instances,
            self::expand($dtstart, $rule, $exdate, count($instances) + ($bounded ? 1 : 0)),
        );
    }

    /**
     * @return iterable<string, array{string, string, list<string>, list<string>}>
     */
    public static function theVectors(): iterable
    {
        foreach (self::vectors() as $number => $vector) {
            yield sprintf('§%s %s (%s)', $vector['section'], $vector['description'], $vector['rule']) => [
                $vector['dtstart'],
                $vector['rule'],
                $vector['exdate'],
                $vector['instances'],
            ];

            unset($number);
        }
    }

    /**
     * **The set covers every example the memo publishes.** A vector set that
     * quietly left one out would answer R-RRULE-06 with less than it claims,
     * so the count is asserted against the thirty-nine examples of §3.8.5.3
     * and the forty-two rules they give.
     */
    public function testTheSetCoversEveryPublishedExample(): void
    {
        $vectors = self::vectors();
        $descriptions = [];

        foreach ($vectors as $vector) {
            $descriptions[$vector['description']] = true;
        }

        self::assertCount(42, $vectors, 'the rules §3.8.5.3 publishes');
        self::assertCount(39, $descriptions, 'the examples §3.8.5.3 publishes');
    }

    /**
     * **And every vector carries the memo's own answer beside it.** The
     * transcription is only auditable where the text it came from is there to
     * compare with.
     */
    public function testEveryVectorCarriesThePublishedAnswer(): void
    {
        foreach (self::vectors() as $vector) {
            self::assertNotSame('', $vector['published'], $vector['description']);
            self::assertNotSame([], $vector['instances'], $vector['description']);
        }
    }

    /**
     * The vector set as it is published in the repository.
     *
     * @return list<array{section: string, description: string, zone: string,
     *                    dtstart: string, rule: string, exdate: list<string>,
     *                    published: string, instances: list<string>}>
     */
    private static function vectors(): array
    {
        $raw = file_get_contents(__DIR__ . '/../../../vectors/rfc5545-recurrence.json');

        self::assertIsString($raw, 'the vector set is readable');

        $vectors = json_decode($raw, true, 512, JSON_THROW_ON_ERROR);

        self::assertIsArray($vectors);

        /**
         * @var list<array{section: string, description: string, zone: string,
         *                 dtstart: string, rule: string, exdate: list<string>,
         *                 published: string, instances: list<string>}> $vectors
         */
        return $vectors;
    }

    /**
     * The recurrence set of one vector, as the instances are written.
     *
     * @param non-empty-string $dtstart
     * @param non-empty-string $rule
     * @param list<string> $exdate
     *
     * @return list<string>
     */
    private static function expand(string $dtstart, string $rule, array $exdate, int $take): array
    {
        $event = new Component('VEVENT');
        $event->add(new Property('DTSTART', $dtstart));
        $event->add(new Property('RRULE', $rule));

        foreach ($exdate as $written) {
            $event->add(new Property('EXDATE', $written));
        }

        $instances = [];

        foreach (ExpandedSet::of($event)->instances() as $instance) {
            $instances[] = $instance->encode();

            if (count($instances) === $take) {
                break;
            }
        }

        return $instances;
    }
}
